# Generated by Django 2.2 on 2022-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
