# Generated by Django 2.2 on 2022-05-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220504_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sender',
        ),
    ]
